/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author: Alberto Gil de la Fuente
 */

package atm;
unit OperationUnit;
import atm.Tries;


rule "authorization of operations"
when
    $operation : /operations[verified == true, date_expired == false, correctPin == true, tries == Tries.NOT_EXPIRED, balance >= price, limit >= price]
then
    // IF I WANT TO DEBUG THE CODE, I CAN PRINT HERE WHATEVER I WANT System.out.println( op );
    System.out.println( $operation + " authorized. ");
    // Student, please try to do this instead of modify like before. What is the difference?
    //$operation.setAuthorized(true);
    // or
    modify ($operation) { setAuthorized(true)}
// operation set cambia el valor del objeto en java, pero el motor de reglas no se entera. El operation SÍ
//AVISA al motor de reglas.
end

rule "invalid verification"
when
    $operation : /operations[verified == false]
then
    System.out.println( $operation + " not authorized due to lack of verification. ");
    modify ($operation) { setAuthorized(false)}
    operationsUnauthorizedNotVerified.add($operation);
end

rule "exceeded limit"
when
    $operation : /operations[limit < price]
then
    System.out.println( $operation + " not authorized due to limit. ");
    modify ($operation) { setAuthorized(false)}
    operationsUnauthorizedExceededLimit.add($operation);
end

query FindAuthorizedOperations
    $operations : /operations[ authorized == true]
end

rule "incorrect PIN"
when
    $o :/operations [correctPin==false]
then
    System.out.println("Operation denied: Incorrect PIN");
    modify ($o) { setAuthorized(false)}
    // NEW SETS add the operation
    operationsUnauthorizedIncorrectPin.add($o);
end


rule "Tries expired"
when
    $o:/operations[tries==Tries.EXPIRED]
then
    System.out.println("Operation denied: Tries expired");
    modify($o) { setAuthorized(false) };
end

rule "No money"
when $o:/operations[balance<price]
then
    System.out.println("No enough money");
    operationsUnauthorizedNoMoney.add($o);
modify($o) { setAuthorized(false)}
end

rule "Expired card"
when
    $o : /operations[date_expired == true]
then
    System.out.println("Operation denied, card is expired");
    modify($o) { setAuthorized(false) };
end

