package dss; // MUY IMP. Debe coincidir con el package de las clases java
unit FeatureUnit; // El nombre de la clase que implementa RuleUnitData

import adduct.Adduct;
import lipid.Peak;
import dss.Feature;
import dss.LabelledPeak;
import dss.LabelledAdductFeature;

// dollar: nombre temporal, apodo
// dos puntos: guardar esto en ....
// corchetes: filtros o condiciones
// barra inclinada, fuente de datos. en que DataStore de la FeatureUnit hay que mirar

// FIRST RULE. HIGH PRIORITY FOR GROUPING.
rule "Deconvolution: Group by RT and neutral mass" // nombre de la regla
salience 10 // fuerzo a que esta regla se intente ejecutar primero para todos los picos (x lo de unknowns)
when
    // Buscamos un pico inicial. ES COMO UN PIVOTE.
    // busca en el DataStore de peaks, llama a ese pico p1.
    // coge su masa mz1 y su tiempo rt1
    $p1: /peaks[ $mz1 : mz, $rt1 : rt ]

    // Cogemos una hipótesis de aducto para este primer pico (ej: ¿y si p1 es M+H?)
    $a1: /knownAdducts
    // Buscamos otro pico diferente que esté en la misma ventana de RT (0.3 mins)
    $p2: /peaks[ this != $p1, $mz2 : mz, Math.abs(rt - $rt1) <= 0.3 ]

    // Cogemos otra hipótesis de aducto para el segundo pico (ej: ¿y si p2 es M+Na?)
    $a2: /knownAdducts[ this != $a1 ]

    // EL CÁLCULO:
    // Comprobamos si la Masa Neutra calculada para el pico 1 (usando aducto 1)
    // es casi igual a la del pico 2 (usando aducto 2)
    // Si coinciden es que vienen de la misma molécula
    // EVAL sirve para hacer matematicas en drools
    eval( Math.abs(Adduct.getMonoisotopicMassFromMZ($mz1, $a1) -
                   Adduct.getMonoisotopicMassFromMZ($mz2, $a2)) <= 0.01 )
    then
    // calculamos la media de las dos en vez de la masa hipotetica
        double m1 = Adduct.getMonoisotopicMassFromMZ($mz1, $a1);
        double m2 = Adduct.getMonoisotopicMassFromMZ($mz2, $a2);
        double mMedia = (m1 + m2) / 2.0;

        // determinamos el nombre del aducto principal, MAYOR PICO DE INTENSIDAD
        String mainName = ($p1.getIntensity() >= $p2.getIntensity()) ? $a1.getLabel() : $a2.getLabel();

        //Feature creation
        Feature f = new Feature(mMedia, mainName);

        f.addPeak($p1);
        f.addPeak($p2);
        features.add(f);

        // CREAR LabelledAdductFeature
        LabelledAdductFeature laf = new LabelledAdductFeature(f, mMedia, mainName);
        laf.addLabelledPeak(new LabelledPeak($p1, $a1));
        laf.addLabelledPeak(new LabelledPeak($p2, $a2));

        labelledFeatures.add(laf);

        System.out.println("Masa " + String.format("%.4f", mMedia));
    end

// RULE 2, LOW PRIORITY
rule "Single peaks (Unknown Adduct)"
salience -10
when
    // take a peak
    $p: /peaks

    // condition: not in a feature
    not /features[ groupedPeaks contains $p ]
then
    // create a Feature Unknown ("mass 0")
    Feature f = new Feature(0.0, "Unknown");
    f.addPeak($p);
    features.add(f);

    System.out.println("Single peak: " + $p.getId() + " to feature 'Unknown'");
end

// Query para poder extraer los resultados
query GetFeatures
    $f: /features
end

query GetLabelledFeatures
    $lf: /labelledFeatures
end





    /*
    CODIGO ANTIGUO
    // masa neutra calculada
    double mHipotetica = Adduct.getMonoisotopicMassFromMZ($mz1, $a1);

    // Crear la Feature indicando la relacion de aductos
    // constructor: Feature(monoisotopicmass, adductLabel)
    Feature f = new Feature(mHipotetica, $a1.getLabel() + "/" + $a2.getLabel());

    // add the peaks to the group
    f.addPeak($p1);
    f.addPeak($p2);

    // guardo la Feature en el DataStore para que Drools pueda acceder
    features.add(f);

    // printeo info de lo que acaba de pasar
    System.out.println("*** Peaks paired: " + $p1.getId() + " y " + $p2.getId() +
                       " are M=" + String.format("%.4f", mHipotetica));
                       end
                       */

